version: '3.8'

services:
  alloy:
    command: [
      run,
      --server.http.listen-addr=0.0.0.0:12345,
      /etc/alloy/config.alloy,
    ]
    container_name: alloy
    image: grafana/alloy:v1.3.0
    ports:
      - 12345:12345
      - 4317:4317
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy

  flask-dummy:
    build:
      context: ./flask-dummy
      dockerfile: Dockerfile
    container_name: flask-dummy
    ports:
      - 8080:5000
    stop_signal: SIGINT
    volumes:
      - .:/flask-dummy

  grafana:
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    image: grafana/grafana:11.1.3
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./grafana:/etc/grafana/provisioning

  loki:
    command: --config.file=/etc/loki/loki-config.yaml
    container_name: loki
    image: grafana/loki:3.1.0
    ports:
      - 3100:3100
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/loki-config.yaml
